language: cpp

matrix:
  include:
  - os: osx
  
install:
- brew update
- brew install qt5
- brew link --force qt5

script:
- qmake Gen4IDs.pro
- make

before_deploy:
- "/usr/local/Cellar/qt/5.11.1/bin/macdeployqt Gen4IDs.app -dmg -verbose=2"
- zip -r Gen4IDs-macOS.zip Gen4IDs.dmg

deploy:
  provider: releases
  api_key:
    secure: bgAoKW6rgdT7HNTTEE+Q1fbmp+p40G4688EDZztM7jI+lKnfUB47eUekau0otyS2Y/Nk2VHX4gaPSu8WNnhpmAwZPzDsnBXWTw7fijt3Z6pfAwPqxVWAeD9xqP5ShLa/hJ/L02tMV4tgfQQDiPcfJrxd9O2TB6SbYiw+ql6ez09ZK8k3PzrhMybpPLE0qu8VsDgg75RM6vUSohEE0SPdNO6MIPSTVOqOAwyRBUzsMmDRn9O8QwKk/spE4gvvApYAnpYJ1x3Lyo1GhVDSvj5AphOG7q2zrugTarEavDDhWbaaGFErmsUdmrkFPdLQ/wWiaowBEnm4DzfpaxztmGZeNJTsX60xdqiY1DnFQRguWWC654/WMGCoCCPl0MV4xZhDSlOCrfP1tve4diRpG2mlqy/McFmB58O2cc0yCrAP+KfZiztxXAFfK2rsu2BYVE5SjF2rq3d1xj4Mo6e2FywGJhXMxSLTxTfloYXEMxRvkaL0FJPlv8zMUt+7uNA6QHtAKOHTN398qsxJzXUpPYBeLpz6Mree/QPI++ilgnDDjawYea7PLB+IbVmFb8QR69oYW4b15RrO++K7FSx8dWu222jLW/SEBaeZlWu7ol8GtStPTy6uRY6i01l0KQdAza8JFnBcyd8NG+P4EWZ27YnzfScEArnSMU+7BeA0LCwY6x8=
  file: Gen4IDs-macOS.zip
  skip_cleanup: true
  on:
    tags: true
