language: cpp

matrix:
  include:
    - os: osx
  
install:
  - brew update
  - brew install qt5
  - brew link --force qt5

script:
  - qmake Gen4IDs.pro
  - make -j $(sysctl -n hw.physicalcpu)

before_deploy:
  - /usr/local/Cellar/qt/5.13.2/bin/macdeployqt Gen4IDs.app -dmg -verbose=2
  - zip -r Gen4IDs-macOS.zip Gen4IDs.dmg

deploy:
  provider: releases
  api_key:
    secure: zq7riFPVWmkiVLczsXj7RTyuElDb3QoppIOWN6/OGviAcnZ+8WDePeNcZ9zaULnl6iwVf/hnKcckxbNzZdETHBM7ikCR3LQ8VXCth7GovcbrkMlrOuslZOEDfF+S5uSU7UNHWdlx2H6jtOSlOhvroPzwkXdyBt9DrCkz00CU41+ZNaczF5A+1gHPdHfYnO0gyoSOFalqde/F2scsjqE4kBB8e29YVCdpZAX54YVU62l2QPy/texELWPT0mTv72/VXRizzJ63zA3enxaiZ5UbQvI/C4ZCE4NztKcRun4qU4M2nQJz/H0w58H4YLlbf97XLtLrv2t7b3vvp2kjzNGPq33SHZEpESkuauX7AzhveAWc19v9Zt6Kjn3NrlywERDfoulyX6q6TsQw0982D7fGQczyeQXMiVF18tGrSvDkt42jeoQ1rdrYTp/u/S83OYynTsPclNB/nfUwefgqjpLYynVamJI0/B8FIQGmHKVEN+MOYlSgT9lqbKrcD/QR3XtxPIyV9Z68a6x37u75Js4Gu9op8hor0bvKSefShyT2hq3jIIda26J45lXtHHtX5Lq8gdt7FtY09km3odNNgdUumB4QJiCQgOnoGdJzpL+wyW9dU+atEBSId4ephSKfEmJZlJJadExEzOYnEN5gvZuQpaI7JZUlvSsavfZh7ipcbd4=
  file: "Gen4IDs-macOS.zip"
  skip_cleanup: true
  on:
    repo: Admiral-Fish/Gen3IDs
    tags: true
