environment:
    matrix:
        # Windows
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          QTDIR: C:\Qt\5.11\msvc2017_64
          OS: windows
        # Linux
        - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
          OS: linux

install:
    # Windows
    - cmd: set PATH=%QTDIR%\bin;C:\Qt\Tools\QtCreator\bin;%PATH%
    - cmd: call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"
    # Linux
    - sh: sudo service docker start
    
build_script:
    # Windows
    - cmd: qmake Gen4IDs.pro
    - cmd: jom -j %NUMBER_OF_PROCESSORS%
    # Linux
    - sh: docker run -w="/app" -v "$(pwd)":/app rabits/qt:5.12-desktop sudo /opt/Qt/5.12.0/gcc_64/bin/qmake
    - sh: docker run -w="/app" -v "$(pwd)":/app rabits/qt:5.12-desktop sudo make -j 4

after_build:
    # Windows
    - cmd: md Gen4IDs-windows
    - cmd: move release\Gen4IDs.exe Gen4IDs-windows\Gen4IDs.exe 
    - cmd: windeployqt --release --no-translations --no-angle --no-plugins --no-opengl-sw Gen4IDs-windows\Gen4IDs.exe
    - cmd: del Gen4IDs-windows\vcredist*.exe
    - cmd: del Gen4IDs-windows\vc_redist*.exe
    - cmd: xcopy /I %QTDIR%\plugins\platforms\qwindows.dll Gen4IDs-windows\platforms\
    - cmd: 7z a Gen4IDs-windows.zip Gen4IDs-windows\
    # Linux
    - sh: zip -r Gen4IDs-linux.zip Gen4IDs
    
artifacts:
    - path: Gen4IDs-%OS%.zip

deploy:
    provider: GitHub
    auth_token:
        secure: u3c5wUq11csZ77TpgKMImu9U+ibNiviMcEpTuQXmqp1YGSHA/+u5FhqZ3KRZBAQX
    artifact: Gen4IDs-%OS%.zip
    on:
        APPVEYOR_REPO_TAG: true
